#
# rust-kcov/Dockerfile
#
# Debian-based container with rustc/cargo and 'kcov' - a
# coverage program which can analyze the code coverage of
# rust tests.
#

FROM debian:${DEBIAN_VERSION} AS builder

RUN apt-get update -qy \
 && apt-get install -qy --no-install-recommends \
	binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev \
	wget cmake ninja-build g++ python3-minimal ca-certificates
RUN wget -c -q $KCOV_URL -O - | tar xz -C /usr/src --strip-components 1
RUN cmake -S /usr/src -B /usr/src -DCMAKE_INSTALL_PREFIX=/opt/local -DCMAKE_BUILD_TYPE=Release -Wno-dev -GNinja \
 && cmake --build /usr/src --target install \
 && strip /opt/local/bin/*

FROM rust:${RUST_VERSION}-${DEBIAN_VERSION}
COPY --from=builder /opt/local/ /usr/local/
COPY --from=builder /usr/lib/x86_64-linux-gnu/libdw.so.1 /usr/lib/x86_64-linux-gnu/
COPY --from=builder /usr/share/doc/libdw1/copyright /usr/share/doc/libdw1/copyright

COPY kcov-rust /usr/bin/


#======================#
# Finalize Environment #
#======================#
WORKDIR /home
