#
# akubera/kcov/Dockerfile.in
#

FROM debian:jessie-slim


ENV DEBIAN_FRONTEND=noninteractive


#============================#
# Install Build Dependencies #
#============================#
RUN apt-get update -qq \
 && apt-get install -yqq --no-install-recommends  \
      cmake g++ make pkg-config python-minimal ca-certificates \
      libdw-dev libcurl4-openssl-dev binutils-dev \
      libiberty-dev zlib1g-dev libelf-dev \
      gcc git curl \
#=========================#
# Download and build kcov #
#=========================#
 && curl -Ls $KCOV_DOWNLOAD_URL | tar xz \
 && cd $KCOV_BUILD_DIR && cmake . && make install \
 && cd - \
#=========#
# Cleanup #
#=========#
 && rm -r $KCOV_BUILD_DIR \
 && apt-get remove -yqq make cmake g++ python-minimal pkg-config \
 && apt-get autoremove -yqq \
 && rm -rf /var/lib/apt/lists/*

